# GitHub Pages configuration for PranaVerse: Mindfulness
title: PranaVerse - Mindfulness
description: Yoga, breathing exercises, healing frequencies and meditation journeys
url: "https://innnervision.github.io"
baseurl: "/Mindfulness-Garden"
theme: null
